### ISSUE TITLE
Duplicates image data for images that originally share the same buffer view

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/gltf-pipeline#416]
Really any objects that share the same resources (shared buffer view, shared data uri) will end up duplicating that resource when the embedded glTF is written out.

Test model: [box-duplicate.gltf.txt](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/2288961/box-duplicate.gltf.txt)

Found while testing https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/302

**Comment by freezy** [comment]
Is anyone working on this? Just spent hours figuring out why some of my scenes actually *increased* in size after running through gltf-pipeline with Draco enabled.
