### ISSUE TITLE
KHR_techniques_webgl missing after updating model from gltf v1.0 to gltf v2.0

### ISSUE THREAD

**Issue by tkazik** [CesiumGS/gltf-pipeline#417]
I tried to update some gltf v1.0 models to v2.0 using this nice pipeline.
If I understood correctly, this pipeline does so by using [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl), which still seems to have draft status according the readme.

The validator as well as cesium complain about the not yet supported gltf extension, see:

![gltf-pipeline](https://user-images.githubusercontent.com/15689124/44298687-b6a1c400-a2e7-11e8-9f63-f67a9efb7051.png)

Will the issue on the cesium side be solved, once this is merged?
https://github.com/AnalyticalGraphicsInc/cesium/pull/6805

What about the validator?

Have a nice weekend

**Comment by lilleyse** [comment]
Yeah Cesium will be able to load those models once https://github.com/AnalyticalGraphicsInc/cesium/pull/6805 is merged. I'm not sure what the plan is for the validator or other engines.

**Comment by donmccurdy** [comment]
@lilleyse now that #6805 has been merged, do you know whether there's an easy way to preview glTF 2.0 `KHR_techniques_webgl` in Cesium? I'm testing https://www.virtualgis.io/gltfviewer/ but getting:

> RuntimeError: Unsupported glTF Extension: KHR_techniques_webgl

I also get an error in VSCode.

**Comment by lilleyse** [comment]
@emackey do you know what would need to be fixed from the VSCode side?

I can't think of other viewers out there that are up to date.

**Comment by emackey** [comment]
Is there a sample model that shows the problem?  I tried running CesiumAir.gltf through the pipeline and the result seems to work in VSCode's Cesium preview.  (It almost works in the ThreeJS preview, but the textures seem to be missing).

Also, click the "Extensions" button in VSCode, and check that glTF-Tools says version 2.1.17 or higher.  If not you will need to update VSCode and/or the extension.

**Comment by emackey** [comment]
Actually the screenshot above looks like version 2.1.14.  You'll need to update VSCode and then update the extension.

**Comment by donmccurdy** [comment]
I'm testing the VSCode extension 2.1.17 with Cesium, and https://www.virtualgis.io/gltfviewer/. The only result I see in VSCode is this:

<img width="463" alt="screen shot 2018-11-20 at 10 05 06 am" src="https://user-images.githubusercontent.com/1848368/48793482-f217aa00-ecab-11e8-9fe6-ce189ffcfc78.png">

I'm not sure how to access the script error, though. Let me see if I can share the model.

**Comment by donmccurdy** [comment]
I can't share the model publicly, but emailed you a copy. Thanks!

**Comment by katSchmid** [comment]
Has this been solved already? Thanks

**Comment by lilleyse** [comment]
@katSchmid I think so, thanks for the ping
