### ISSUE TITLE
gltf to glb works in command line but not in nodejs. 

### ISSUE THREAD

**Issue by anupamdas2012** [CesiumGS/gltf-pipeline#524]
Hi, I have a gltf file im trying to convert to glb via a nodejs script.
if I do the conversion from gltf to glb via the command line tools. the glb is correct.
if i do the conversion with code with the same input gltf/bin files, the conversion does not work and the resulting .glb file gives me this error when validating it: 

I am using the latest gltf-pipeline via npm. let me know.

Error | Message | Pointer
-- | -- | --
UNDEFINED_PROPERTY | Property 'asset' must be defined. | /
UNEXPECTED_PROPERTY	Unexpected property.	/type
UNEXPECTED_PROPERTY	Unexpected property.	/data

**Comment by lilleyse** [comment]
@anupamdas2012 are you able to share the gltf model and exact command that you used?

**Comment by anupamdas2012** [comment]
yes. 
buggy model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF

code snippet.---------

const gltfPipeline = require('gltf-pipeline');
const fsExtra = require('fs-extra');
const gltfToGlb = gltfPipeline.gltfToGlb;
const glbToGltf = gltfPipeline.glbToGltf;

//upload .gltf file to server .gltf file is converted to .glb
//input .gltf and .bin file
//requirement: user must select both the .gltf and acompanying .bin file
fileoptimizerouter.post('/uploadGLTF', upload.array('upload-', 12), (req, res, next) => {

  req.files.forEach(function(file){
    const ext = path.extname(file.originalname); 
    if(ext===".gltf")
    {
      console.log("converting gltf file: " + file.path);
      const gltf = fsExtra.readFileSync(file.path);
      gltfToGlb(gltf).then(function(results) {
          fsExtra.writeFileSync('output/model.glb', results.glb);
      })
    }
   // check mimetype for .bin file. 
   //this outouts: mimetype:  mimetypeapplication/macbinary
   //encoding: encoding7bit
    if(ext===".bin")
    {
      console.log("bin mimetype" + file.mimetype);
      console.log("bin encoding" + file.encoding);
    }
  });

  //convert to GLB
  /*
  const gltf = fsExtra.readFileSync(gltf_file.path);
  gltfToGlb(gltf)
  .then(function(results) {
      fsExtra.writeFileSync('output/model.glb', results.glb);
  });
  */
  res.send('done!');
  
})

**Comment by anupamdas2012** [comment]
some more info:
I am using gltf-pipeline 2.1.6

.gltf file is a valid jason file after upload
.bin file mimetype is checkd. it is "mimetypeapplication/macbinary"
with 7bit encding.
as you can see i am using multer to multi select the .gltf and .bin files and upload to server before processing

**Comment by lilleyse** [comment]
@anupamdas2012 

There's two issues in the code:
* `readFileSync` should be `readJsonSync`
* Since the model uses external resources you need to pass in `resourceDirectory`.

This code should work, assuming the model is in the same folder as the script:

```js
const gltfPipeline = require('gltf-pipeline');
const fsExtra = require('fs-extra');
const gltfToGlb = gltfPipeline.gltfToGlb;

const filePath = 'Buggy.gltf';
const gltf = fsExtra.readJsonSync(filePath);

const options = {
    resourceDirectory : '.'
};

gltfToGlb(gltf, options).then(function(results) {
    fsExtra.writeFileSync('model.glb', results.glb);
}).catch(function(error) {
    console.log(error);
});
```

**Comment by anupamdas2012** [comment]
it works! thanks for the  response and support. I must have missed something in the docs regarding the resource directory options for gltf files that have seperate .bin files. this is useful to know for those of us dealing with files that contain seperate .bin files. Thanks!
