### ISSUE TITLE
png & jpeg to KTX GPU texture

### ISSUE THREAD

**Issue by pierreglibert** [CesiumGS/gltf-pipeline#530]
Hi community :)
I read this : 
https://github.com/CesiumGS/gltf-pipeline/pull/204
I'm really interested to know if it's possible to convert png and jpeg to gpu texture (DXT, PVR, ECT, etc) with gltf-pipeline ?

Thanks for your help.

**Comment by lilleyse** [comment]
@pierreglibert it used to be possible with older versions of gltf-pipeline but it was removed because it was cumbersome to deal with so many different compressed texture formats. Instead we are keeping our eyes on basis texture compression: https://github.com/KhronosGroup/glTF/pull/1751.

**Comment by pierreglibert** [comment]
Hi @lilleyse :)
Thanks for your answer.
