### ISSUE TITLE
how to compress bin file to draco format bin

### ISSUE THREAD

**Issue by jakkypan** [CesiumGS/gltf-pipeline#531]
![image](https://user-images.githubusercontent.com/15864446/77025691-b8080680-69cc-11ea-85ec-465f2b96a7d4.png)

i have know how to compress the  gltf file to draco gltf file, but how to compress bin file to draco format bin? I can found the command

**Comment by lilleyse** [comment]
@jakkypan are you referring to the .drc binary file described in https://github.com/google/draco?

Or do you just want to apply draco and save the .bin file separately from the glTF?

**Comment by jakkypan** [comment]
yes,i want to re-save the bin file with draco to get a smaller bin file.

i saw someone use the glTF Pipeline to achieve the purpose，just like show below:
![image](https://user-images.githubusercontent.com/15864446/77075810-df42f000-6a2d-11ea-8f1d-f5516aed0795.png)

but i don't know how to do using the  glTF Pipeline command line. so is it workable to use glTF Pipeline command line to compress bin file?

**Comment by lilleyse** [comment]
@jakkypan try this:

`gltf-pipeline -i model.gltf -o model-draco.gltf -d -s`

The `-s` will write separate buffers and textures instead of embedding them in the glTF.

**Comment by jakkypan** [comment]
you don't understand my words, i want compress the bin file, using your command, it just compress the gltf, not the bin file.

how can i compress the bin file ??

**Comment by lilleyse** [comment]
@jakkypan it's not possible to just compress the bin file by itself, the whole glTF needs to be passed in.

You should notice the .bin get smaller when Draco is applied to the glTF.

The model in this screenshot is from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF converted with the `-d -s` options.

<img width="957" alt="Screen Shot 2020-03-19 at 10 34 36 PM" src="https://user-images.githubusercontent.com/915398/77131410-f552af80-6a31-11ea-956a-070b8ce15be8.png">

**Comment by jakkypan** [comment]
yes, i hava try the **duck** gltf material using the command, and it works fine.

but i compress myself gltf material as the same, it did not work,as below:
![image](https://user-images.githubusercontent.com/15864446/77158205-c8f46d00-6add-11ea-9946-8af38039f3f9.png)

is there any special operations when create the bin file?

**Comment by lilleyse** [comment]
Hm that's not expected.. @jakkypan would you be able the share the glTF so I could test it?

**Comment by jakkypan** [comment]
thank you for your persistent reply!

i hava create a repository in github, the link is: [https://github.com/jakkypan/testgltf](https://github.com/jakkypan/testgltf)

**Comment by lilleyse** [comment]
Thanks @jakkypan.

After looking at the file draco is working as expected, it's just that the model has so much animation data which the draco extension doesn't compress. There's not much we can do from the gltf-pipeline side.
