### ISSUE TITLE
abort(TypeError: n[q[((q[(Ct >> 2)] + 20) >> 2)]] is not a function)

### ISSUE THREAD

**Issue by lantsang** [CesiumGS/gltf-pipeline#547]
Hi, I want to compress my gltf files with gltf-pipeline, but the terminal always report errors. Can anyone know about the reasons of the exception above?
the command was `gltf-pipeline -i model.gltf -o modelDraco.gltf -d`

**Comment by lilleyse** [comment]
@lantsang I'm not seeing this error. What version of Node are you using?

**Comment by lantsang** [comment]
> @lantsang I'm not seeing this error. What version of Node are you using?

Hi, lilleyse, the node version is 12.18.2 LTS.
I found that if the file is large, such as 3.1 GB, there will be errors. If I use a smaller file ,such as 1.1 GB, then the test is normal.

**Comment by kring** [comment]
Node.js is unfortunately unable to allocate a buffer larger than 2GB, no matter how much memory you have.
https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length
😧 

With a 3.1GB file, you _may_ be able to work around this by splitting your glTF into multiple buffers. For example, put different attributes in different buffers.

**Comment by lantsang** [comment]
> Node.js is unfortunately unable to allocate a buffer larger than 2GB, no matter how much memory you have.
> https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length
> 😧
> 
> With a 3.1GB file, you _may_ be able to work around this by splitting your glTF into multiple buffers. For example, put different attributes in different buffers.

Wow! that's it. Really appreciate it, you saved my life :)

**Comment by lantsang** [comment]
> @lantsang I'm not seeing this error. What version of Node are you using?

Hi, lilleyse, a more friendly error message would have been better for this, how do you think?

**Comment by kring** [comment]
I'm not sure we have much control over the error message, it comes straight from Node.js.

**Comment by lantsang** [comment]
> I'm not sure we have much control over the error message, it comes straight from Node.js.

Hi, kring, thank you for the message, that's enough for it. :)
