### ISSUE TITLE
Question: Does any company provides this converter as an API as a Service ?

### ISSUE THREAD

**Issue by Aarbel** [CesiumGS/gltf-pipeline#557]
Hi @cesiumgs-admin 

Thanks a lot for this beautiful library !

I don't want to build my own servers and run this code on it, manage the scalability etc..., do you know an API as a service to use it ? (of course a paying one)

Thanks a lot for the tips !

**Comment by OmarShehata** [comment]
@Aarbel you can Cesium ion for this! See: https://cesium.com/ion/. You can host a model as a glTF after running it through gltf-pipeline, or if you have large models you can tile them into 3D Tiles.

Let me know if this works for you. If you have any follow up questions I'd post in the Cesium community forum: https://community.cesium.com/.

**Comment by Aarbel** [comment]
@OmarShehata which kind of files can we convert with Cesium ? UI not really clear to see what we can do ! Thanks a lot

**Comment by OmarShehata** [comment]
There's a good reference on supported file types here: https://cesium.com/docs/tutorials/uploading/. If you have questions about your specific data or have a suggestion, please [post on the community forum](https://community.cesium.com/).

**Comment by Aarbel** [comment]
![image](https://user-images.githubusercontent.com/25119847/91839068-bb2b4200-ec4e-11ea-94a7-8200f97c9136.png)

Where can i find Draco conversion ? 

Do you also plan to support ifc conversion to gltf ?

**Comment by Aarbel** [comment]
@OmarShehata ?

**Comment by OmarShehata** [comment]
@Aarbel please post your question to the Cesium forum (https://community.cesium.com/) so others in the community can see the answers/contribute to the discussion.
