### ISSUE TITLE
FeatureRequest: Decompress Draco compressed file.

### ISSUE THREAD

**Issue by gonnavis** [CesiumGS/gltf-pipeline#567]
I want to decompress gltf/glb files because Blender can only import uncompressed files.
I did not find a decompression command in your tool. Now I can only decompress through the threejs editor, it's a bit troublesome.
Could you please add decompress function to your cli tool?

**Comment by lilleyse** [comment]
@gonnavis we're tracking this in https://github.com/CesiumGS/gltf-pipeline/issues/382 so I'll close this as a duplicate. Thanks for the suggestion, I included a link to this issue there.
