### ISSUE TITLE
Increment version number to 4.x.x for hasExtension -> usesExtension

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/gltf-pipeline#601]
We renamed `hasExtension` to `usesExtension` here: https://github.com/CesiumGS/gltf-pipeline/commit/154858625ad110059b64a8efdb0cb2717cf791bf

I think this should've prompted us to increment the version number to 4.x.x, right?

**Comment by lilleyse** [comment]
`hasExtension`/`usesExtension` actually isn't part of the public API and didn't warrant a version bump. The problem is we use non-public API functions in some of our internal repos.

The public API is here: https://github.com/CesiumGS/gltf-pipeline/blob/main/index.js

**Comment by getinthedamnbox** [comment]
Got it, thanks. Closing this.
