### ISSUE TITLE
Meshes are corrupted

### ISSUE THREAD

**Issue by schwarzsky** [CesiumGS/gltf-pipeline#614]
![chrome_sKt4pxMHjl](https://user-images.githubusercontent.com/25959527/174654300-88390654-66fb-48a9-9ceb-8f253929d94e.png)
As you can see, you can saw the back of the meshes. This is not supposed to be happen. Any idea? Tried lowering compressionSize.

**Comment by lilleyse** [comment]
@schwarzsky could you post the full command? Is this just a problem with Draco compression?

**Comment by schwarzsky** [comment]
First used `npx gltf-pipeline -i SnowyTerrain.glb -d --draco.compressionLevel 10 -o Snowy.glb`
Then downed scale to 10 to 1.

I don't own the builds its not right to post GLB file but if you want it anyway i can get permission i think.

Also yes, this is a problem with Draco compression. Before compression model looks quite right. @lilleyse

**Comment by schwarzsky** [comment]
Just used `--draco.unifiedQuantization` and solved the issue. Thanks!
