### ISSUE TITLE
Consider disambiguating resource names

### ISSUE THREAD

**Issue by javagl** [CesiumGS/gltf-pipeline#634]
When resources (like external buffer- or image references) are created via the `options.separate` flag, then their names are assigned automatically. This is happening around [`writeResources.getName`](https://github.com/CesiumGS/gltf-pipeline/blob/dc213115d2ca12bd5afae00770e48c019ac7d2d5/lib/writeResources.js#L194). The names are somewhat generic - something like `buffer0.bin`. One could consider _prefixing_ these names with the base name of the input file, to disambiguate them. For example, when processing a `Duck.glb`, the files could be named `Duck_buffer0.bin`.

(The use case is that one might to batch-process multiple files in one directory, and write the results into one directory. When the input files `Duck.glb` and `Triangle.glb` both generate a `buffer.bin`, then the user has no obvious way to handle this: The `separateResources` _do_ contain the names like `buffer0.bin` as the key, but this cannot be changed at the client side - at least not without manually doing some hacky `gltf.buffers[i].uri = myNewName`).

**Comment by lilleyse** [comment]
It should already prefix with the base name of the input file. E.g. if I run

```
node bin/gltf-pipeline.js -i ./specs/data/2.0/box-textured-embedded/box-textured-embedded.gltf -o ~/Desktop/box.gltf --separate
```

I get three files:

* box.gltf
* box.bin
* box0.png

If you're calling `processGltf` or equivalent programmatically you'll need to pass in `options.name` for it to get prefixed.

**Comment by javagl** [comment]
>  pass in `options.name` for it to get prefixed.

That was the missing piece.
