### ISSUE TITLE
I used draco(-d) compression, why put my custom data to the loss. There are two files in the attachment that have not been compressed. The customized data in 100.glb still exists after compression, but the customized data in 102.glb is lost.

### ISSUE THREAD

**Issue by sui0312feng** [CesiumGS/gltf-pipeline#650]
[testfile.zip](https://github.com/CesiumGS/gltf-pipeline/files/13421169/testfile.zip)

I used draco(-d) compression, why put my custom data to the loss. There are two files in the attachment that have not been compressed. The customized data in 100.glb still exists after compression, but the customized data in 102.glb is lost.

The custom data is placed in the first and second elements of the bufferview array.

![1700534748870](https://github.com/CesiumGS/gltf-pipeline/assets/9710113/16cef346-95f3-4a97-bbbd-f2208c785d5a)
![1700534929657](https://github.com/CesiumGS/gltf-pipeline/assets/9710113/0c56d346-89bd-4096-a35e-048584275a30)

**Comment by lilleyse** [comment]
@sui0312feng there are some [validation](https://github.khronos.org/glTF-Validator/) issues with 102.glb. Is it possible to fix those and then try again? I copied the relevant errors below:

```
        "messages": [
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 127 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/0"
            },
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 12451 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/1"
            },
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 16559 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/2"
            },
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 65519 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/3"
            },
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 73583 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/4"
            },
            {
                "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
                "message": "Accessor's total byteOffset 76271 isn't a multiple of componentType length 4.",
                "severity": 0,
                "pointer": "/accessors/5"
            },
            {
                "code": "BUFFER_VIEW_TARGET_OVERRIDE",
                "message": "Override of previously set bufferView target or usage. Initial: 'IndexBuffer', new: 'VertexBuffer'.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/0/attributes/_FEATURE_ID_0"
            },
            {
                "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_UNSIGNED_INT",
                "message": "Mesh attributes cannot use UNSIGNED_INT component type.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/0/attributes/_FEATURE_ID_0"
            },
            {
                "code": "BUFFER_VIEW_TARGET_OVERRIDE",
                "message": "Override of previously set bufferView target or usage. Initial: 'IndexBuffer', new: 'VertexBuffer'.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/1/attributes/_FEATURE_ID_0"
            },
            {
                "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_UNSIGNED_INT",
                "message": "Mesh attributes cannot use UNSIGNED_INT component type.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/1/attributes/_FEATURE_ID_0"
            },
```

**Comment by sui0312feng** [comment]
Modified the above problem, the compression still lost the custom data
[No_0.zip](https://github.com/CesiumGS/gltf-pipeline/files/13435027/No_0.zip)


> @sui0312feng there are some [validation](https://github.khronos.org/glTF-Validator/) issues with 102.glb. Is it possible to fix those and then try again? I copied the relevant errors below:
> 
> ```
>         "messages": [
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 127 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/0"
>             },
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 12451 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/1"
>             },
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 16559 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/2"
>             },
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 65519 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/3"
>             },
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 73583 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/4"
>             },
>             {
>                 "code": "ACCESSOR_TOTAL_OFFSET_ALIGNMENT",
>                 "message": "Accessor's total byteOffset 76271 isn't a multiple of componentType length 4.",
>                 "severity": 0,
>                 "pointer": "/accessors/5"
>             },
>             {
>                 "code": "BUFFER_VIEW_TARGET_OVERRIDE",
>                 "message": "Override of previously set bufferView target or usage. Initial: 'IndexBuffer', new: 'VertexBuffer'.",
>                 "severity": 0,
>                 "pointer": "/meshes/0/primitives/0/attributes/_FEATURE_ID_0"
>             },
>             {
>                 "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_UNSIGNED_INT",
>                 "message": "Mesh attributes cannot use UNSIGNED_INT component type.",
>                 "severity": 0,
>                 "pointer": "/meshes/0/primitives/0/attributes/_FEATURE_ID_0"
>             },
>             {
>                 "code": "BUFFER_VIEW_TARGET_OVERRIDE",
>                 "message": "Override of previously set bufferView target or usage. Initial: 'IndexBuffer', new: 'VertexBuffer'.",
>                 "severity": 0,
>                 "pointer": "/meshes/0/primitives/1/attributes/_FEATURE_ID_0"
>             },
>             {
>                 "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_UNSIGNED_INT",
>                 "message": "Mesh attributes cannot use UNSIGNED_INT component type.",
>                 "severity": 0,
>                 "pointer": "/meshes/0/primitives/1/attributes/_FEATURE_ID_0"
>             },
> ```

Modified the above problem, the compression still lost the custom data。
[No_0.zip](https://github.com/CesiumGS/gltf-pipeline/files/13435033/No_0.zip)

**Comment by sui0312feng** [comment]
> @sui0312feng thanks for sending over the new file.
> 
> It still looks like there are problems. No_0.glb is on the left, 100.glb is on the right.
> 
> * `properties` should be an object (I think this is the main problem)
> * `_class` should be `class`
> * `_name` should be `name`
> 
> ![image](https://user-images.githubusercontent.com/915398/284933145-340f1bb5-8074-4a3d-be4c-81610f43be9c.png)

thank you!  you are right!  issue was settled !
