### ISSUE TITLE
error:failed adding attribute TEXCOORD_0

### ISSUE THREAD

**Issue by sui0312feng** [CesiumGS/gltf-pipeline#657]
![1711449389589](https://github.com/CesiumGS/gltf-pipeline/assets/9710113/ec6f8d69-803f-4bec-ae5e-ec003dffbba2)
[t75.zip](https://github.com/CesiumGS/gltf-pipeline/files/14757029/t75.zip)

**Comment by sui0312feng** [comment]
t75.zip contains test files

**Comment by lilleyse** [comment]
@sui0312feng [glTF Validator](https://github.khronos.org/glTF-Validator/) reports a lot of errors for this model. Is it possible to fix those and try again?

This seems to be the most relevant error:

```
            {
                "code": "MESH_PRIMITIVE_UNEQUAL_ACCESSOR_COUNT",
                "message": "All accessors of the same primitive must have the same count.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/1/attributes/TEXCOORD_0"
            },
```
