### ISSUE TITLE
Error: Draco encoding failed.

### ISSUE THREAD

**Issue by YIyiyi-3** [CesiumGS/gltf-pipeline#662]
![image](https://github.com/CesiumGS/gltf-pipeline/assets/94603146/1a23d538-3334-4335-88b6-b7fe6cdd4943)
我在进行gltf文件压缩Draco时一直再报错误
![image](https://github.com/CesiumGS/gltf-pipeline/assets/94603146/db4d4257-35a9-4e42-bb78-261110abed2f)

**Comment by majid-saeed** [comment]
@YIyiyi-3  how it is closed? any solution?
